### ISSUE TITLE
When press the stop mining the entire program has no response, and it required force end process then restart.

### ISSUE THREAD

**Issue by jeong760** [rgx91/BWTool#6] opened 2021-03-02 06:51 UTC
Dears,

When I press the STOP MINING the entire program required an end force process and restart it again. 
Is there any method to prevent this problem?

![image](https://user-images.githubusercontent.com/18043565/109609633-f01d4080-7b6e-11eb-86e0-aeb91151630c.png)

![image](https://user-images.githubusercontent.com/18043565/109609921-61f58a00-7b6f-11eb-9e81-89c51fb7ab75.png)

Best Regards,
John Ahn

**Comment by rgx91** [comment] 2021-03-02 07:47
I cant reproduce it on my side :(
For me everything working on a different pc (directly not using dev machine for testing) using the release files.
Also build it from source and worked as well, cancellation token working greatly.[
![Clipboard01](https://user-images.githubusercontent.com/46424242/109614957-99464580-7b33-11eb-9b9f-027f9e80870f.jpg)
](url)
Can you tell me which options are you used?
It is always happening?
Are you brainwallet mining or private key searching when you cant stop the mining?

**Comment by jeong760** [comment] 2021-03-02 08:01
Dears,

 

Yes, my option is
- Using Enter
- Checked Lookup compressed addresses 
- Count of sha256 operation on the string is 1or 2, but usually 1 I selected.
- I loaded the around 122,300 addresses of bitcoin which I exacted from the BTC client chain.
- I loaded the Englishdic.txt file

The attached files are
[english.txt](https://github.com/rgx91/BWTool/files/6067035/english.txt)
[data3.txt](https://github.com/rgx91/BWTool/files/6067038/data3.txt)

My laptop has 8GB RAM and 256GB SSD with dual cores i5 CPU. 

Best Regards,
John Ahn

**Comment by jeong760** [comment] 2021-03-02 08:03
It seems only tried one key in the data3.txt file as I think. 

![image](https://user-images.githubusercontent.com/18043565/109617068-45f6e600-7b79-11eb-8922-bcf392d4672a.png)

**Comment by jeong760** [comment] 2021-03-02 08:04
![image](https://user-images.githubusercontent.com/18043565/109617227-7a6aa200-7b79-11eb-8647-b7058f5f5a90.png)

**Comment by jeong760** [comment] 2021-03-03 09:56
Dears,

Have you checked the code?  I tried to recompile a code seceral times but result is same as before

I don't know why it suspended when I press the stop button

Best Regards, 
John Ahn

**Comment by rgx91** [comment] 2021-03-11 13:46
I cant reproduce it with your files either.
If you are able to debug it from visual studio that would be awesome.
Maybe its some kind of exception which is hidden in miner thread.
Also you can try to run the tool with higher privilages, maybe it help
![Clipboard01](https://user-images.githubusercontent.com/46424242/110796752-986e8b80-8278-11eb-80e2-a31af67a4099.png)

**Comment by rgx91** [comment] 2021-03-20 09:09
Cant reproduce it, closing it for now

**Closed as completed by rgx91** 2021-03-20 09:09 UTC
